In [1]:
!pip install tensorflow

  Using cached protobuf-4.25.6-cp310-abi3-win_amd64.whl.metadata (541 bytes)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.3
    Uninstalling protobuf-5.29.3:
      Successfully uninstalled protobuf-5.29.3


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-tools 1.70.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.23.4 which is incompatible.
langchain-google-genai 1.0.5 requires langchain-core<0.3,>=0.2.0, but you have langchain-core 0.3.40 which is incompatible.
opentelemetry-proto 1.28.1 requires protobuf<6.0,>=5.0, but you have protobuf 4.23.4 which is incompatible.


In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [3]:
# Here we are loading the data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 4s 0us/step


In [4]:
#Here we are reshaping the data
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1)


In [6]:
#Here we are checking the shape after reshaping
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [7]:
# And here we are normalizing the pixel values

X_train = X_train/255
X_test = X_test/255

In [8]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [9]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [10]:
model = Sequential()

In [11]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D((2,2)))

In [13]:
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [14]:
#adding output layer
model.add(Dense(10,activation='softmax'))

In [15]:
#compiling the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
#fitting the model
model.fit(X_train,y_train,epochs=10)

Epoch 1/10


1875/1875 [==============================] - 24s 11ms/step - loss: 0.1630 - accuracy: 0.9507
Epoch 2/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0544 - accuracy: 0.9833
Epoch 3/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0363 - accuracy: 0.9883
Epoch 4/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0249 - accuracy: 0.9917
Epoch 5/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0173 - accuracy: 0.9943
Epoch 6/10
1875/1875 [==============================] - 22s 11ms/step - loss: 0.0145 - accuracy: 0.9953
Epoch 7/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0118 - accuracy: 0.9961
Epoch 8/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0088 - accuracy: 0.9972
Epoch 9/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0074 - accuracy: 0.9975
Epoch 10/10
1875/1875 [==============================] - 22s 1

In [17]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0612 - accuracy: 0.9859


[0.06118867173790932, 0.9858999848365784]