In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset  = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

data cleaning spliting dataset into dependent and independent variables

In [4]:
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(Y)

[1 0 1 ... 1 1 0]


Label encoding using scikit for geography(hot encoding) and gender(0 or 1)

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_2 = LabelEncoder()
X[:,2] = label_X_2.fit_transform(X[:,2])

In [8]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('ohe',OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype = np.str_)
X = X[:,1:]

In [10]:
print(X)

[['0.0' '0.0' '619' ... '1' '1' '101348.88']
 ['0.0' '1.0' '608' ... '0' '1' '112542.58']
 ['0.0' '0.0' '502' ... '1' '0' '113931.57']
 ...
 ['0.0' '0.0' '709' ... '0' '1' '42085.58']
 ['1.0' '0.0' '772' ... '1' '0' '92888.52']
 ['0.0' '0.0' '792' ... '1' '0' '38190.78']]


Spliting data into training and testing

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

Feature Scaling 

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
pd.DataFrame(X_train)

0         1         2         3         4         5         6   \
0    -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717   
1     1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2    -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3    -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4    -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.754865 -0.573694 -0.582970 -1.091687 -0.656016 -0.339364  0.703104   
7996 -0.569844  1.743090  1.478815 -1.091687 -1.613058 -0.339364  0.613060   
7997 -0.569844 -0.573694  0.901515  0.916013 -0.368904  0.006661  1.361474   
7998 -0.569844  1.743090 -0.624205 -1.091687 -0.081791  1.390762 -1.215717   
7999  1.754865 -0.573694 -0.284011 -1.091687  0.875251 -1.377440  0.511364   

            7         8         9         10  
0     0.809503  0.642595 -1.032270  1.106432  
1    -0.921591  0.642595  0.968738 -0.748664  
2    -0.921591  0.642595 -1.032270  1.485335  
3    -0.921591  0.642595 -1.032270  1.276528  
4     0.809503  0.642595  0.968738  0.558378  
...        ...       ...       ...       ...  
7995  0.809503  0.642595  0.968738  1.091330  
7996 -0.921591  0.642595  0.968738  0.131760  
7997  0.809503  0.642595 -1.032270  1.412320  
7998  0.809503  0.642595  0.968738  0.844321  
7999 -0.921591  0.642595 -1.032270  0.324725  

[8000 rows x 11 columns]

Building the A-NN

In [15]:
from keras.models import Sequential

In [16]:
from keras.layers import Dense

In [17]:
classifier = Sequential()

In [21]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu', input_dim=11)) # layer 1

In [22]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu')) # layer 2

In [23]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid')) # output layer

In [26]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.7936 - loss: 0.5671
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7885 - loss: 0.4384
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8017 - loss: 0.4189
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8026 - loss: 0.4123
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8220 - loss: 0.4253
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8249 - loss: 0.4204
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8278 - loss: 0.4195
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8338 - loss: 0.4069
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8372 - loss: 0.4057
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8340 - loss: 0.4147
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8342 - loss: 0.4182
Epoch 12/100
800/800 ━━━━━━━━━━━━━━━━━━━━

In [28]:
Y_pred = classifier.predict(X_test)
Y_pred = (Y_pred>0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [29]:
print(Y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test,Y_pred)

In [32]:
cm

array([[1531,   64],
       [ 250,  155]], dtype=int64)

In [33]:
accuracy_score(Y_test,Y_pred)

0.843